version: "3.8"

services:
  redis:
    image: redis:6.0.7
    container_name: redis
    restart: always
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - redis_volume_data:/data
    ports:
      - 6380:6379

  redis_insight:
    image: redislabs/redisinsight:1.14.0
    container_name: redis_insight
    restart: always
    ports:
      - 8001:8001
    volumes:
      - redis_insight_volume_data:/db

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pointmaster
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d/
    restart: always

  # Load balancer service
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80" 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf 
    depends_on:
      - cashier-service-1
      - cashier-service-2
      - admin-service
      - auth-service
      - customer-service
    restart: always

  admin-service:
    image: admin-service
    build:
      context: ./admin-service
      dockerfile: Dockerfile
    environment:
      - ACCESS_TOKEN_SECRET=panadura
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=pointmaster
      - REDIS_URL=redis://redis:6379
      - REGISTRATION_SECRET=panadura
    depends_on:
      - db
      - redis
    restart: on-failure

  # First instance of cashier service
  cashier-service-1:
    image: cashier-service
    build:
      context: ./cashier-service
      dockerfile: Dockerfile
    environment:
      - ACCESS_TOKEN_SECRET=panadura
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=pointmaster
    depends_on:
      - db
    restart: on-failure

  # Second instance of cashier service
  cashier-service-2:
    image: cashier-service
    build:
      context: ./cashier-service
      dockerfile: Dockerfile
    environment:
      - ACCESS_TOKEN_SECRET=panadura
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=pointmaster
    depends_on:
      - db
    restart: on-failure

  auth-service:
    image: auth-service
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    environment:
      - ACCESS_TOKEN_SECRET=panadura
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=pointmaster
    depends_on:
      - db
    restart: on-failure

  customer-service:
    image: customer-service
    build:
      context: ./customer-service
      dockerfile: Dockerfile
    environment:
      - ACCESS_TOKEN_SECRET=panadura
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=pointmaster
    depends_on:
      - db
    restart: on-failure

volumes:
  redis_volume_data:
  redis_insight_volume_data:
  db_data:
