version: '3.8'

services:
  db:
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pointmaster
    ports:
      - "3308:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d/ 
    restart: always

  admin-service:
    build:
      context: ./admin-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - ACCESS_TOKEN_SECRET=panadura
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=pointmaster
    depends_on:
      - db
    restart: on-failure

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - ACCESS_TOKEN_SECRET=panadura
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=pointmaster
    depends_on:
      - db
    restart: on-failure

  cashier-service:
    build:
      context: ./cashier-service
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - ACCESS_TOKEN_SECRET=panadura
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=pointmaster
    depends_on:
      - db
    restart: on-failure

  customer-service:
    build:
      context: ./customer-service
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    environment:
      - ACCESS_TOKEN_SECRET=panadura
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=pointmaster
    depends_on:
      - db
    restart: on-failure


